#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOTROTIMVIEC_08
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HOTROTIMVIEC")]
	public partial class HTTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMINISTRATION(ADMINISTRATION instance);
    partial void UpdateADMINISTRATION(ADMINISTRATION instance);
    partial void DeleteADMINISTRATION(ADMINISTRATION instance);
    partial void InsertVIECLAM(VIECLAM instance);
    partial void UpdateVIECLAM(VIECLAM instance);
    partial void DeleteVIECLAM(VIECLAM instance);
    partial void InsertDONVITUYENDUNG(DONVITUYENDUNG instance);
    partial void UpdateDONVITUYENDUNG(DONVITUYENDUNG instance);
    partial void DeleteDONVITUYENDUNG(DONVITUYENDUNG instance);
    partial void InsertDONVITUYENDUNG_VIECLAM(DONVITUYENDUNG_VIECLAM instance);
    partial void UpdateDONVITUYENDUNG_VIECLAM(DONVITUYENDUNG_VIECLAM instance);
    partial void DeleteDONVITUYENDUNG_VIECLAM(DONVITUYENDUNG_VIECLAM instance);
    partial void InsertNGUOILAODONG(NGUOILAODONG instance);
    partial void UpdateNGUOILAODONG(NGUOILAODONG instance);
    partial void DeleteNGUOILAODONG(NGUOILAODONG instance);
    partial void InsertQUYENHAN(QUYENHAN instance);
    partial void UpdateQUYENHAN(QUYENHAN instance);
    partial void DeleteQUYENHAN(QUYENHAN instance);
    #endregion
		
		public HTTVDataContext() : 
				base(global::HOTROTIMVIEC_08.Properties.Settings.Default.HOTROTIMVIECConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HTTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HTTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMINISTRATION> ADMINISTRATIONs
		{
			get
			{
				return this.GetTable<ADMINISTRATION>();
			}
		}
		
		public System.Data.Linq.Table<VIECLAM> VIECLAMs
		{
			get
			{
				return this.GetTable<VIECLAM>();
			}
		}
		
		public System.Data.Linq.Table<DON_TUYENDUNG> DON_TUYENDUNGs
		{
			get
			{
				return this.GetTable<DON_TUYENDUNG>();
			}
		}
		
		public System.Data.Linq.Table<DONVITUYENDUNG> DONVITUYENDUNGs
		{
			get
			{
				return this.GetTable<DONVITUYENDUNG>();
			}
		}
		
		public System.Data.Linq.Table<DONVITUYENDUNG_TAIKHOAN> DONVITUYENDUNG_TAIKHOANs
		{
			get
			{
				return this.GetTable<DONVITUYENDUNG_TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<DONVITUYENDUNG_VIECLAM> DONVITUYENDUNG_VIECLAMs
		{
			get
			{
				return this.GetTable<DONVITUYENDUNG_VIECLAM>();
			}
		}
		
		public System.Data.Linq.Table<NGUOILAODONG> NGUOILAODONGs
		{
			get
			{
				return this.GetTable<NGUOILAODONG>();
			}
		}
		
		public System.Data.Linq.Table<NGUOILAODONG_TAIKHOAN> NGUOILAODONG_TAIKHOANs
		{
			get
			{
				return this.GetTable<NGUOILAODONG_TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<QUYENHAN> QUYENHANs
		{
			get
			{
				return this.GetTable<QUYENHAN>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SV_CheckDN")]
		public int SV_CheckDN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Taikhoan", DbType="NVarChar(50)")] string taikhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Matkhau", DbType="NVarChar(50)")] string matkhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> checkDN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taikhoan, matkhau, checkDN);
			checkDN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMINISTRATION")]
	public partial class ADMINISTRATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAdmin;
		
		private string _Ten;
		
		private string _SDT;
		
		private string _CMND;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private int _Vitri;
		
		private EntityRef<QUYENHAN> _QUYENHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAdminChanging(int value);
    partial void OnMaAdminChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnVitriChanging(int value);
    partial void OnVitriChanged();
    #endregion
		
		public ADMINISTRATION()
		{
			this._QUYENHAN = default(EntityRef<QUYENHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAdmin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaAdmin
		{
			get
			{
				return this._MaAdmin;
			}
			set
			{
				if ((this._MaAdmin != value))
				{
					this.OnMaAdminChanging(value);
					this.SendPropertyChanging();
					this._MaAdmin = value;
					this.SendPropertyChanged("MaAdmin");
					this.OnMaAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="Int NOT NULL")]
		public int Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					if (this._QUYENHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVitriChanging(value);
					this.SendPropertyChanging();
					this._Vitri = value;
					this.SendPropertyChanged("Vitri");
					this.OnVitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUYENHAN_ADMINISTRATION", Storage="_QUYENHAN", ThisKey="Vitri", OtherKey="MaQ", IsForeignKey=true)]
		public QUYENHAN QUYENHAN
		{
			get
			{
				return this._QUYENHAN.Entity;
			}
			set
			{
				QUYENHAN previousValue = this._QUYENHAN.Entity;
				if (((previousValue != value) 
							|| (this._QUYENHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUYENHAN.Entity = null;
						previousValue.ADMINISTRATIONs.Remove(this);
					}
					this._QUYENHAN.Entity = value;
					if ((value != null))
					{
						value.ADMINISTRATIONs.Add(this);
						this._Vitri = value.MaQ;
					}
					else
					{
						this._Vitri = default(int);
					}
					this.SendPropertyChanged("QUYENHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VIECLAM")]
	public partial class VIECLAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaViec;
		
		private string _TenViec;
		
		private string _MoTa;
		
		private decimal _MucLuong;
		
		private EntitySet<DONVITUYENDUNG_VIECLAM> _DONVITUYENDUNG_VIECLAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaViecChanging(int value);
    partial void OnMaViecChanged();
    partial void OnTenViecChanging(string value);
    partial void OnTenViecChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnMucLuongChanging(decimal value);
    partial void OnMucLuongChanged();
    #endregion
		
		public VIECLAM()
		{
			this._DONVITUYENDUNG_VIECLAMs = new EntitySet<DONVITUYENDUNG_VIECLAM>(new Action<DONVITUYENDUNG_VIECLAM>(this.attach_DONVITUYENDUNG_VIECLAMs), new Action<DONVITUYENDUNG_VIECLAM>(this.detach_DONVITUYENDUNG_VIECLAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViec", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaViec
		{
			get
			{
				return this._MaViec;
			}
			set
			{
				if ((this._MaViec != value))
				{
					this.OnMaViecChanging(value);
					this.SendPropertyChanging();
					this._MaViec = value;
					this.SendPropertyChanged("MaViec");
					this.OnMaViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenViec", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string TenViec
		{
			get
			{
				return this._TenViec;
			}
			set
			{
				if ((this._TenViec != value))
				{
					this.OnTenViecChanging(value);
					this.SendPropertyChanging();
					this._TenViec = value;
					this.SendPropertyChanged("TenViec");
					this.OnTenViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MucLuong", DbType="Decimal(18,0) NOT NULL")]
		public decimal MucLuong
		{
			get
			{
				return this._MucLuong;
			}
			set
			{
				if ((this._MucLuong != value))
				{
					this.OnMucLuongChanging(value);
					this.SendPropertyChanging();
					this._MucLuong = value;
					this.SendPropertyChanged("MucLuong");
					this.OnMucLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VIECLAM_DONVITUYENDUNG_VIECLAM", Storage="_DONVITUYENDUNG_VIECLAMs", ThisKey="MaViec", OtherKey="MaViec")]
		public EntitySet<DONVITUYENDUNG_VIECLAM> DONVITUYENDUNG_VIECLAMs
		{
			get
			{
				return this._DONVITUYENDUNG_VIECLAMs;
			}
			set
			{
				this._DONVITUYENDUNG_VIECLAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONVITUYENDUNG_VIECLAMs(DONVITUYENDUNG_VIECLAM entity)
		{
			this.SendPropertyChanging();
			entity.VIECLAM = this;
		}
		
		private void detach_DONVITUYENDUNG_VIECLAMs(DONVITUYENDUNG_VIECLAM entity)
		{
			this.SendPropertyChanging();
			entity.VIECLAM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DON_TUYENDUNG")]
	public partial class DON_TUYENDUNG
	{
		
		private System.Nullable<int> _MaNLD;
		
		private System.Nullable<int> _Id;
		
		private System.Nullable<System.DateTime> _NgayDK;
		
		private int _TrangThai;
		
		public DON_TUYENDUNG()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNLD", DbType="Int")]
		public System.Nullable<int> MaNLD
		{
			get
			{
				return this._MaNLD;
			}
			set
			{
				if ((this._MaNLD != value))
				{
					this._MaNLD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this._NgayDK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int NOT NULL")]
		public int TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this._TrangThai = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVITUYENDUNG")]
	public partial class DONVITUYENDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDV;
		
		private string _TenDV;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private int _QuyMo;
		
		private bool _TrangThai;
		
		private EntitySet<DONVITUYENDUNG_VIECLAM> _DONVITUYENDUNG_VIECLAMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnQuyMoChanging(int value);
    partial void OnQuyMoChanged();
    partial void OnTrangThaiChanging(bool value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public DONVITUYENDUNG()
		{
			this._DONVITUYENDUNG_VIECLAMs = new EntitySet<DONVITUYENDUNG_VIECLAM>(new Action<DONVITUYENDUNG_VIECLAM>(this.attach_DONVITUYENDUNG_VIECLAMs), new Action<DONVITUYENDUNG_VIECLAM>(this.detach_DONVITUYENDUNG_VIECLAMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyMo", DbType="Int NOT NULL")]
		public int QuyMo
		{
			get
			{
				return this._QuyMo;
			}
			set
			{
				if ((this._QuyMo != value))
				{
					this.OnQuyMoChanging(value);
					this.SendPropertyChanging();
					this._QuyMo = value;
					this.SendPropertyChanged("QuyMo");
					this.OnQuyMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit NOT NULL")]
		public bool TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVITUYENDUNG_DONVITUYENDUNG_VIECLAM", Storage="_DONVITUYENDUNG_VIECLAMs", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<DONVITUYENDUNG_VIECLAM> DONVITUYENDUNG_VIECLAMs
		{
			get
			{
				return this._DONVITUYENDUNG_VIECLAMs;
			}
			set
			{
				this._DONVITUYENDUNG_VIECLAMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DONVITUYENDUNG_VIECLAMs(DONVITUYENDUNG_VIECLAM entity)
		{
			this.SendPropertyChanging();
			entity.DONVITUYENDUNG = this;
		}
		
		private void detach_DONVITUYENDUNG_VIECLAMs(DONVITUYENDUNG_VIECLAM entity)
		{
			this.SendPropertyChanging();
			entity.DONVITUYENDUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVITUYENDUNG_TAIKHOAN")]
	public partial class DONVITUYENDUNG_TAIKHOAN
	{
		
		private string _MaDV_TaiKhoan;
		
		private string _Matkhau;
		
		private int _Vitri;
		
		public DONVITUYENDUNG_TAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV_TaiKhoan", DbType="NVarChar(10)")]
		public string MaDV_TaiKhoan
		{
			get
			{
				return this._MaDV_TaiKhoan;
			}
			set
			{
				if ((this._MaDV_TaiKhoan != value))
				{
					this._MaDV_TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this._Matkhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="Int NOT NULL")]
		public int Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					this._Vitri = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONVITUYENDUNG_VIECLAM")]
	public partial class DONVITUYENDUNG_VIECLAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaDV;
		
		private int _MaViec;
		
		private int _QuyMo;
		
		private System.Nullable<System.DateTime> _TGBatDau;
		
		private System.Nullable<System.DateTime> _TGKetThuc;
		
		private EntityRef<DONVITUYENDUNG> _DONVITUYENDUNG;
		
		private EntityRef<VIECLAM> _VIECLAM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaDVChanging(string value);
    partial void OnMaDVChanged();
    partial void OnMaViecChanging(int value);
    partial void OnMaViecChanged();
    partial void OnQuyMoChanging(int value);
    partial void OnQuyMoChanged();
    partial void OnTGBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnTGBatDauChanged();
    partial void OnTGKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnTGKetThucChanged();
    #endregion
		
		public DONVITUYENDUNG_VIECLAM()
		{
			this._DONVITUYENDUNG = default(EntityRef<DONVITUYENDUNG>);
			this._VIECLAM = default(EntityRef<VIECLAM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DONVITUYENDUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViec", DbType="Int NOT NULL")]
		public int MaViec
		{
			get
			{
				return this._MaViec;
			}
			set
			{
				if ((this._MaViec != value))
				{
					if (this._VIECLAM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaViecChanging(value);
					this.SendPropertyChanging();
					this._MaViec = value;
					this.SendPropertyChanged("MaViec");
					this.OnMaViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyMo", DbType="Int NOT NULL")]
		public int QuyMo
		{
			get
			{
				return this._QuyMo;
			}
			set
			{
				if ((this._QuyMo != value))
				{
					this.OnQuyMoChanging(value);
					this.SendPropertyChanging();
					this._QuyMo = value;
					this.SendPropertyChanged("QuyMo");
					this.OnQuyMoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGBatDau
		{
			get
			{
				return this._TGBatDau;
			}
			set
			{
				if ((this._TGBatDau != value))
				{
					this.OnTGBatDauChanging(value);
					this.SendPropertyChanging();
					this._TGBatDau = value;
					this.SendPropertyChanged("TGBatDau");
					this.OnTGBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKetThuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGKetThuc
		{
			get
			{
				return this._TGKetThuc;
			}
			set
			{
				if ((this._TGKetThuc != value))
				{
					this.OnTGKetThucChanging(value);
					this.SendPropertyChanging();
					this._TGKetThuc = value;
					this.SendPropertyChanged("TGKetThuc");
					this.OnTGKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DONVITUYENDUNG_DONVITUYENDUNG_VIECLAM", Storage="_DONVITUYENDUNG", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DONVITUYENDUNG DONVITUYENDUNG
		{
			get
			{
				return this._DONVITUYENDUNG.Entity;
			}
			set
			{
				DONVITUYENDUNG previousValue = this._DONVITUYENDUNG.Entity;
				if (((previousValue != value) 
							|| (this._DONVITUYENDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DONVITUYENDUNG.Entity = null;
						previousValue.DONVITUYENDUNG_VIECLAMs.Remove(this);
					}
					this._DONVITUYENDUNG.Entity = value;
					if ((value != null))
					{
						value.DONVITUYENDUNG_VIECLAMs.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(string);
					}
					this.SendPropertyChanged("DONVITUYENDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VIECLAM_DONVITUYENDUNG_VIECLAM", Storage="_VIECLAM", ThisKey="MaViec", OtherKey="MaViec", IsForeignKey=true)]
		public VIECLAM VIECLAM
		{
			get
			{
				return this._VIECLAM.Entity;
			}
			set
			{
				VIECLAM previousValue = this._VIECLAM.Entity;
				if (((previousValue != value) 
							|| (this._VIECLAM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VIECLAM.Entity = null;
						previousValue.DONVITUYENDUNG_VIECLAMs.Remove(this);
					}
					this._VIECLAM.Entity = value;
					if ((value != null))
					{
						value.DONVITUYENDUNG_VIECLAMs.Add(this);
						this._MaViec = value.MaViec;
					}
					else
					{
						this._MaViec = default(int);
					}
					this.SendPropertyChanged("VIECLAM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOILAODONG")]
	public partial class NGUOILAODONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNLD;
		
		private string _Ten;
		
		private string _CMND;
		
		private string _GioiTinh;
		
		private System.DateTime _NgaySinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _BangCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNLDChanging(int value);
    partial void OnMaNLDChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.DateTime value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnBangCapChanging(string value);
    partial void OnBangCapChanged();
    #endregion
		
		public NGUOILAODONG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNLD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNLD
		{
			get
			{
				return this._MaNLD;
			}
			set
			{
				if ((this._MaNLD != value))
				{
					this.OnMaNLDChanging(value);
					this.SendPropertyChanging();
					this._MaNLD = value;
					this.SendPropertyChanged("MaNLD");
					this.OnMaNLDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BangCap", DbType="NVarChar(50)")]
		public string BangCap
		{
			get
			{
				return this._BangCap;
			}
			set
			{
				if ((this._BangCap != value))
				{
					this.OnBangCapChanging(value);
					this.SendPropertyChanging();
					this._BangCap = value;
					this.SendPropertyChanged("BangCap");
					this.OnBangCapChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOILAODONG_TAIKHOAN")]
	public partial class NGUOILAODONG_TAIKHOAN
	{
		
		private System.Nullable<int> _MaNLD;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private int _Vitri;
		
		public NGUOILAODONG_TAIKHOAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNLD", DbType="Int")]
		public System.Nullable<int> MaNLD
		{
			get
			{
				return this._MaNLD;
			}
			set
			{
				if ((this._MaNLD != value))
				{
					this._MaNLD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this._Taikhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this._Matkhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="Int NOT NULL")]
		public int Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					this._Vitri = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYENHAN")]
	public partial class QUYENHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaQ;
		
		private string _TenQ;
		
		private string _Mota;
		
		private EntitySet<ADMINISTRATION> _ADMINISTRATIONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQChanging(int value);
    partial void OnMaQChanged();
    partial void OnTenQChanging(string value);
    partial void OnTenQChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public QUYENHAN()
		{
			this._ADMINISTRATIONs = new EntitySet<ADMINISTRATION>(new Action<ADMINISTRATION>(this.attach_ADMINISTRATIONs), new Action<ADMINISTRATION>(this.detach_ADMINISTRATIONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQ", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaQ
		{
			get
			{
				return this._MaQ;
			}
			set
			{
				if ((this._MaQ != value))
				{
					this.OnMaQChanging(value);
					this.SendPropertyChanging();
					this._MaQ = value;
					this.SendPropertyChanged("MaQ");
					this.OnMaQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQ", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string TenQ
		{
			get
			{
				return this._TenQ;
			}
			set
			{
				if ((this._TenQ != value))
				{
					this.OnTenQChanging(value);
					this.SendPropertyChanging();
					this._TenQ = value;
					this.SendPropertyChanged("TenQ");
					this.OnTenQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUYENHAN_ADMINISTRATION", Storage="_ADMINISTRATIONs", ThisKey="MaQ", OtherKey="Vitri")]
		public EntitySet<ADMINISTRATION> ADMINISTRATIONs
		{
			get
			{
				return this._ADMINISTRATIONs;
			}
			set
			{
				this._ADMINISTRATIONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADMINISTRATIONs(ADMINISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.QUYENHAN = this;
		}
		
		private void detach_ADMINISTRATIONs(ADMINISTRATION entity)
		{
			this.SendPropertyChanging();
			entity.QUYENHAN = null;
		}
	}
}
#pragma warning restore 1591
