<?xml version="1.0" encoding="utf-8"?><Database Name="HOTROTIMVIEC" Class="HTTVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=THUC\SQL;Initial Catalog=HOTROTIMVIEC;Integrated Security=True" SettingsObjectName="_08_HOTROTIMVIEC.Properties.Settings" SettingsPropertyName="HOTROTIMVIECConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ADMINISTRATION" Member="ADMINISTRATIONs">
    <Type Name="ADMINISTRATION">
      <Column Name="MaAdmin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Taikhoan" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Vitri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QUYENHAN_ADMINISTRATION" Member="QUYENHAN" ThisKey="Vitri" OtherKey="MaQ" Type="QUYENHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VIECLAM" Member="VIECLAMs">
    <Type Name="VIECLAM">
      <Column Name="MaViec" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenViec" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Association Name="VIECLAM_DONVITUYENDUNG_VIECLAM" Member="DONVITUYENDUNG_VIECLAMs" ThisKey="MaViec" OtherKey="MaViec" Type="DONVITUYENDUNG_VIECLAM" />
    </Type>
  </Table>
  <Table Name="dbo.DON_TUYENDUNG" Member="DON_TUYENDUNGs">
    <Type Name="DON_TUYENDUNG">
      <Column Name="MaNLD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDK" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DONVITUYENDUNG_VIECLAM_DON_TUYENDUNG" Member="DONVITUYENDUNG_VIECLAM" ThisKey="Id" OtherKey="Id" Type="DONVITUYENDUNG_VIECLAM" IsForeignKey="true" />
      <Association Name="NGUOILAODONG_DON_TUYENDUNG" Member="NGUOILAODONG" ThisKey="MaNLD" OtherKey="MaNLD" Type="NGUOILAODONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVI_Image" Member="DONVI_Images">
    <Type Name="DONVI_Image">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="DONVITUYENDUNG_DONVI_Image" Member="DONVITUYENDUNG" ThisKey="MaDV" OtherKey="MaDV" Type="DONVITUYENDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVITUYENDUNG" Member="DONVITUYENDUNGs">
    <Type Name="DONVITUYENDUNG">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DONVITUYENDUNG_DONVI_Image" Member="DONVI_Images" ThisKey="MaDV" OtherKey="MaDV" Type="DONVI_Image" />
      <Association Name="DONVITUYENDUNG_DONVITUYENDUNG_TAIKHOAN" Member="DONVITUYENDUNG_TAIKHOANs" ThisKey="MaDV" OtherKey="MaDV_TaiKhoan" Type="DONVITUYENDUNG_TAIKHOAN" />
      <Association Name="DONVITUYENDUNG_DONVITUYENDUNG_VIECLAM" Member="DONVITUYENDUNG_VIECLAMs" ThisKey="MaDV" OtherKey="MaDV" Type="DONVITUYENDUNG_VIECLAM" />
    </Type>
  </Table>
  <Table Name="dbo.DONVITUYENDUNG_TAIKHOAN" Member="DONVITUYENDUNG_TAIKHOANs">
    <Type Name="DONVITUYENDUNG_TAIKHOAN">
      <Column Name="MaDV_TaiKhoan" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Vitri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DONVITUYENDUNG_DONVITUYENDUNG_TAIKHOAN" Member="DONVITUYENDUNG" ThisKey="MaDV_TaiKhoan" OtherKey="MaDV" Type="DONVITUYENDUNG" IsForeignKey="true" />
      <Association Name="QUYENHAN_DONVITUYENDUNG_TAIKHOAN" Member="QUYENHAN" ThisKey="Vitri" OtherKey="MaQ" Type="QUYENHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONVITUYENDUNG_VIECLAM" Member="DONVITUYENDUNG_VIECLAMs">
    <Type Name="DONVITUYENDUNG_VIECLAM">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaViec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuyMo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TGBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DONVITUYENDUNG_VIECLAM_DON_TUYENDUNG" Member="DON_TUYENDUNGs" ThisKey="Id" OtherKey="Id" Type="DON_TUYENDUNG" />
      <Association Name="DONVITUYENDUNG_DONVITUYENDUNG_VIECLAM" Member="DONVITUYENDUNG" ThisKey="MaDV" OtherKey="MaDV" Type="DONVITUYENDUNG" IsForeignKey="true" />
      <Association Name="VIECLAM_DONVITUYENDUNG_VIECLAM" Member="VIECLAM" ThisKey="MaViec" OtherKey="MaViec" Type="VIECLAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOILAODONG" Member="NGUOILAODONGs">
    <Type Name="NGUOILAODONG">
      <Column Name="MaNLD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CMND" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="BangCap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NGUOILAODONG_DON_TUYENDUNG" Member="DON_TUYENDUNGs" ThisKey="MaNLD" OtherKey="MaNLD" Type="DON_TUYENDUNG" />
      <Association Name="NGUOILAODONG_NGUOILAODONG_TAIKHOAN" Member="NGUOILAODONG_TAIKHOANs" ThisKey="MaNLD" OtherKey="MaNLD" Type="NGUOILAODONG_TAIKHOAN" />
      <Association Name="NGUOILAODONG_NGUOILD_Image" Member="NGUOILD_Images" ThisKey="MaNLD" OtherKey="MaNLD" Type="NGUOILD_Image" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOILAODONG_TAIKHOAN" Member="NGUOILAODONG_TAIKHOANs">
    <Type Name="NGUOILAODONG_TAIKHOAN">
      <Column Name="MaNLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Taikhoan" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Matkhau" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Vitri" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NGUOILAODONG_NGUOILAODONG_TAIKHOAN" Member="NGUOILAODONG" ThisKey="MaNLD" OtherKey="MaNLD" Type="NGUOILAODONG" IsForeignKey="true" />
      <Association Name="QUYENHAN_NGUOILAODONG_TAIKHOAN" Member="QUYENHAN" ThisKey="Vitri" OtherKey="MaQ" Type="QUYENHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOILD_Image" Member="NGUOILD_Images">
    <Type Name="NGUOILD_Image">
      <Column Name="MaNLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="NGUOILAODONG_NGUOILD_Image" Member="NGUOILAODONG" ThisKey="MaNLD" OtherKey="MaNLD" Type="NGUOILAODONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYENHAN" Member="QUYENHANs">
    <Type Name="QUYENHAN">
      <Column Name="MaQ" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenQ" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="QUYENHAN_ADMINISTRATION" Member="ADMINISTRATIONs" ThisKey="MaQ" OtherKey="Vitri" Type="ADMINISTRATION" />
      <Association Name="QUYENHAN_DONVITUYENDUNG_TAIKHOAN" Member="DONVITUYENDUNG_TAIKHOANs" ThisKey="MaQ" OtherKey="Vitri" Type="DONVITUYENDUNG_TAIKHOAN" />
      <Association Name="QUYENHAN_NGUOILAODONG_TAIKHOAN" Member="NGUOILAODONG_TAIKHOANs" ThisKey="MaQ" OtherKey="Vitri" Type="NGUOILAODONG_TAIKHOAN" />
    </Type>
  </Table>
  <Function Name="dbo.SV_addDON_TUYENDUNG" Method="SV_addDON_TUYENDUNG">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngayDK" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="check" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_UpdateThongTin_NLD" Method="SV_UpdateThongTin_NLD">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenNLD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="bangcap" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_Check_DV_image" Method="SV_Check_DV_image">
    <Parameter Name="maDV" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="check" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_Check_NLD_image" Method="SV_Check_NLD_image">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="check" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_Check_NLD_image_TrungTen" Method="SV_Check_NLD_image_TrungTen">
    <Parameter Name="tenImage" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="check" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_CheckDN" Method="SV_CheckDN">
    <Parameter Name="Taikhoan" Parameter="taikhoan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Matkhau" Parameter="matkhau" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="checkDN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_Delete_Don_TuyenDung" Method="SV_Delete_Don_TuyenDung">
    <Parameter Name="maNlD" Type="System.Int32" DbType="Int" />
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_ListDVTD_By_MaViec" Method="SV_ListDVTD_By_MaViec">
    <Parameter Name="maviec" Type="System.Int32" DbType="Int" />
    <ElementType Name="SV_ListDVTD_By_MaViecResult">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QuyMo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TGBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SV_LocDon_TD_TheoNgay_ByMaNLDandTenViec" Method="SV_LocDon_TD_TheoNgay_ByMaNLDandTenViec">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="kw" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="kind" Type="System.Int32" DbType="Int" />
    <Parameter Name="trangthai" Type="System.Int32" DbType="Int" />
    <ElementType Name="SV_LocDon_TD_TheoNgay_ByMaNLDandTenViecResult">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenViec" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="NgayDK" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SV_Timkiem_DiaDiem_MaViec" Method="SV_Timkiem_DiaDiem_MaViec">
    <Parameter Name="maViec" Type="System.Int32" DbType="Int" />
    <Parameter Name="keyword" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SV_Timkiem_DiaDiem_MaViecResult">
      <Column Name="MaDV" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QuyMo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TGBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TGKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SV_Timkiem_MucLuong" Method="SV_Timkiem_MucLuong">
    <Parameter Name="mucluong" Type="System.Decimal" DbType="Decimal(18,0)" />
    <ElementType Name="SV_Timkiem_MucLuongResult">
      <Column Name="MaViec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenViec" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SV_Timkiem_TenViec" Method="SV_Timkiem_TenViec">
    <Parameter Name="keyword" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="SV_Timkiem_TenViecResult">
      <Column Name="MaViec" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenViec" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SV_UpdateImage_Link_NLD" Method="SV_UpdateImage_Link_NLD">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="Link" Parameter="link" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_UpdateMatKhauMoi_NLD" Method="SV_UpdateMatKhauMoi_NLD">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="matkhaumoi" Type="System.String" DbType="NVarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SV_Add_ThongTin_TaiKhoan_NLD" Method="SV_Add_ThongTin_TaiKhoan_NLD">
    <Parameter Name="maNLD" Type="System.Int32" DbType="Int" />
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(25)" />
    <Parameter Name="cmnd" Type="System.String" DbType="NVarChar(12)" />
    <Parameter Name="gioitinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="ngaysinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="diachi" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="sdt" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="bangcap" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="taikhoan" Type="System.String" DbType="NVarChar(25)" />
    <Parameter Name="mk" Type="System.String" DbType="NVarChar(25)" />
    <Return Type="System.Int32" />
  </Function>
</Database>